power_all: test-power.o power.o
	gcc -o power_all test-power.o power.o
test-power: test-power.c
	gcc -o test-power -std=gnu99 -pedantic -Wall -Werror test-power.c
power: power.c
	gcc -o power -std=gnu99 -pedantic -Wall -Werror power.c
