step1: step1.c
	gcc -o step1 -std=gnu99 -pedantic -Wall -Werror step1.c

step2: step2.c
	gcc -o step2 -std=gnu99 -pedantic -Wall -Werror step2.c

step3: step3.c
	gcc -o step3 -std=gnu99 -pedantic -Wall -Werror step3.c
